"""add conversation_id to message id

Revision ID: 2c29b965f78b
Revises: bc75b445764a
Create Date: 2020-10-18 00:57:06.572552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c29b965f78b'
down_revision = 'bc75b445764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conservation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_message_conservation_id'), 'message', ['conservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_conservation_id'), table_name='message')
    op.drop_column('message', 'conservation_id')
    # ### end Alembic commands ###
