"""change column name and type

Revision ID: f6ecbfc5c447
Revises: 2c29b965f78b
Create Date: 2020-10-18 01:04:30.257209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ecbfc5c447'
down_revision = '2c29b965f78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.drop_index('ix_message_conservation_id', table_name='message')
    op.drop_column('message', 'conservation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conservation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_message_conservation_id', 'message', ['conservation_id'], unique=False)
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_column('message', 'conversation_id')
    # ### end Alembic commands ###
